//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBIO
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public Nullable<System.DateTime> fechaVenta { get; set; }
        public Nullable<int> idUsuarioComprador { get; set; }
        public Nullable<int> idNegocio { get; set; }
        public Nullable<decimal> total { get; set; }

        [JsonIgnore]
        public virtual Negocio Negocio { get; set; }
        [JsonIgnore]
        public virtual Usuario Usuario { get; set; }
    }
}
